<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'b75fddd1f7e7eb8b31842a903f98367c',
  'MYSQL_PORT' => '3306',
  'MYSQL_ROOT_PASSWORD' => 'root',
  'MYSQL_DATABASE' => 'symfony',
  'MYSQL_USER' => 'symfony',
  'MYSQL_PASSWORD' => 'symfony',
  'PHP_PORT' => '9000',
  'PHP_XDEBUG_MODE' => 'off',
  'PHP_XDEBUG_CLIENT_PORT' => '5902',
  'PHP_XDEBUG_CLIENT_HOST' => 'host.docker.internal',
  'PHPMYADMIN_PORT' => '8080',
  'NGINX_PORT' => '80',
  'NGINX_SYMFONY_SERVER_NAME' => 'symfony.localhost',
);
